[project]
name = "jonbuntu"
version = "0.1.0"
description = "Let's host"
authors = [{name = "Jon", email = "karlsen.jon.a@gmail.com"}]
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "httpx",
    "psutil",
    "jinja2",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "jsbeautifier",
]

[tool.ruff]
line-length = 88
target-version = "py313"
fix = true

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
